//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones
    {
        public int id { get; set; }
        public string nombreOpcion { get; set; }
        public Nullable<int> productoRelacionado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
